UniProjemV3Odev3/MvcProjesi/Controllers/HomeController.cs
using MvcProjesi.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Configuration;
using System.Data.Entity.ModelConfiguration.Conventions;
using Microsoft.Owin;

namespace MvcProjesi.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
            return View();
        }

        //Son 5 makalenin ana sayfaya yükleneceği Action
        public ActionResult TumUrunler()
        {
            //Veritabanından yeni bir nesne oluşturuyoruz.
            MvcProjesiContext db = new MvcProjesiContext();

            //Veritabanından sorgulamayı Linq ile yapıyoruz.
            List<Urun> UrunListe = db.Uruns.OrderByDescending(i => i.Adi).Take(5).ToList();

            //Normal içeriklerde View döndürürken, burada ise PartialView döndürüyoruz.
            //Ayrıca urunListe nesnesini de View'de kullanacağımız şekilde model olarak aktarıyoruz.
            return PartialView(UrunListe);
        }     

       
/*

        public ActionResult EtiketinMakaleleri(int etiketId)
        {
            MvcProjesiContext db = new MvcProjesiContext();
            var geciciListe = (from i in db.Etikets where i.EtiketId == etiketId select i.Makales).ToList();

            //Burada veri içiçe liste halinde geldiği için, içerideki listeyi [0] indexi ile alıp gönderiyoruz.
            return View(geciciListe[0]);
        }

        public ActionResult MakaleDetay(int makaleId)
        {
            MvcProjesiContext db = new MvcProjesiContext();

            //Burada verilen id numarasına göre seçili makaleyi alıyoruz.
            Makale makale = (from i in db.Makales where i.MakaleId == makaleId select i).SingleOrDefault();
            return View(makale);
        }
        public ActionResult YorumMakalesi(int yorumId)
        {
            MvcProjesiContext db = new MvcProjesiContext();

            //Burada verilen yorumId numarasına göre ait olduğu makaleyi alıyoruz.
            Makale makale = (from i in db.Yorums where i.YorumId==yorumId select i.Makale).SingleOrDefault();
            return View(makale);
        }

        */


        // GET: Forms
        public ActionResult Forms()
        {
            return View();
        }
    }
}

UniProjemV3Odev3/MvcProjesi/Controllers/UyelikController.cs
using MvcProjesi.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin;

//MD5 ile şifreyi hashleyerek veritabanına eklemek için aşağıdaki sınıfa ihtiyacımız var.
using System.Security.Cryptography;

namespace MvcProjesi.Controllers
{
    public class UyelikController : Controller
    {
        public ActionResult YeniUyelik()
        {
            return View();
        }

        //Formumuzun geliş metodu Post
        //Dikkat ederseniz aynı isimli, iki adet Action var.
        //Üsttekinin metodu boş olduğu için Get oluyor.
        //Alttakinin üzerinde [HttpPost] olduğu için metodu Post oluyor.
        //Burada eğer sayfa içinden bir form gönderimi yapılmışsa, Post olan Action çağrılır.
        //Normal adres üzerinden sayfaya talepte bulunulursa, Get metodlu olan çağrılır.
        [HttpPost]
        public ActionResult YeniUyelik(Uye model, string textBoxDogum, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (String.IsNullOrEmpty(textBoxDogum))
            {
                //Burada Uye modelimizde olmayan bir elemanla çalıştığımız için, kendimiz elle hata
                //mesajını, sayfadaki hata listesine (@Html.ValidationSummary()) ekliyoruz.
                ModelState.AddModelError("textBoxDogum", "Doğum tarihi boş geçilemez");

                //Hata oluşması halinde sayfayı tekrar yüklüyoruz.
                //Böylelikle otomatik olarak hatalar sayfada gösteriliyor.
                return View();
            }
            int yil = int.Parse(textBoxDogum.Substring(6));
            if (yil > 2002)
            {
                ModelState.AddModelError("textBoxDogum", "Yaşınız 12 den küçük olamaz");
                return View();
            }
            Uye uye = new Uye();
            if (file != null)
            {
                //Sunucuya dosya kaydedilirken, sunucunun dosya sistemini, yolunu bilemeyeceğimiz için
                //Server.MapPath() ile sitemizin ana dizinine gelmiş oluruz. Devamında da sitemizdeki
                //yolu tanımlarız.
                file.SaveAs(Server.MapPath("~/Images/") + file.FileName);
                uye.ResimYol = "/Images/" + file.FileName;
            }
            uye.Ad = model.Ad;
            uye.EPosta = model.EPosta;
            uye.Soyad = model.Soyad;
            uye.UyeOlmaTarih = DateTime.Now;
            uye.WebSite = model.WebSite;
            uye.Sifre = model.Sifre;
            using (MvcProjesiContext db = new MvcProjesiContext())
            {
                db.Uyes.Add(uye);
                db.SaveChanges();

                //İşlemimiz başarıyla biterse, başarılı olduğuna dair bir sayfaya yönlendiriyoruz.
                return RedirectToAction("UyelikBasarili");
            }
        }

        public ActionResult UyelikBasarili()
        {
            return View();
        }
    }
}

UniProjemV3Odev3/MvcProjesi/Views/Home/Index.cshtml
@{
    ViewBag.Title = " ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--Bu div, bizim ana içeriğimiz. Genişliğin, %75'ini almasını ve sola yaslanmasını istedik. -->
<div style="width:75%;float:left">
    <!--Burada Partial View yerine Html.Action metodunu çağırdık-->

    
    @Html.Action("TumUrunler")
</div>
<!--Bu div, bizim yan kenar içeriğimiz. Genişliğin, %25'ini almasını ve sola,
    ana divin yanına, yaslanmasını istedik. -->
<div style="width:25%;float:left">

    <div class="row-fluid">

    </div>
</div>

UniProjemV3Odev3/MvcProjesi/Views/Home/TumUrunler.cshtml
<!--Modelimiz liste olarak geldiği için List<> içerisine aldık-->
@model List<MvcProjesi.Data.Urun>
<div>
    <h2>Tüm Ürünler</h2>
    @{
        //Bu sefer de for döngüsünü kullandık.
        for (int i = 0; i < Model.Count() - 1; i++)
        {
         
            <div style="border:1px solid red">
                <!--Üye bilgilerini alırken Linq yardımıyla, direkt, yorumu yazan üyenin bilgilerine
                    @@Model[i].Uye. şeklinde ulaşabildik.
                    -->
                
                Adı : @Model[i].Adi<br />
                Ders : @Model[i].Ders<br />
                Bölüm : @Model[i].Bolum<br />
                Uni : @Model[i].Universite.Icerik<br />
                <h3>Ürün Bilgileri</h3>
                <!--Üye bilgilerini alırken Linq yardımıyla, direkt, yorumun ait olduğu
                          makelenin bilgilerine @@Model[i].Makale. şeklinde ulaşabildik.
               @*
                Başlık : @Html.ActionLink(@Model[i].Makale.Baslik, "YorumMakalesi", new { yorumId = Model[i].YorumId })
                <h3>Yorumun İçeriği</h3>
                <p>@Model[i].Icerik</p>
                Tarih : @Model[i].Tarih  *@ -->
            </div>
        }
    }
</div>

UniProjemV3Odev3/MvcProjesi/Views/Uyelik/UyelikBasarili.cshtml
@{
    ViewBag.Title = "UyelikBasarili";
}

<h2>Başarıyla Üye Oldunuz</h2>

Tebrikler, sitemize başarıyla üye oldunuz.

UniProjemV3Odev3/MvcProjesi/Views/Uyelik/YeniUyelik.cshtml
@model MvcProjesi.Data.Uye

@{
    ViewBag.Title = "Yeni Üyelik";
}
<!--Layout sayfamızda sayfanın en alt kısmında scripts adlı bir sectionumuz tanımlanmıştı.
    Script ve css kodlarımızı scripts sectionuna koyacağız.
    Detaylı bilgi önceki yazılarımızda vardır.-->
@section scripts{
    <style type="text/css">
        #formKapsayici {
            box-shadow: 0 0 5px gray;
            padding: 25px;
            height: 500px;
        }

        #divSol, #divSag {
            float: left;
            margin-left: 25px;
        }

            #divSol *, #divSag * {
                margin-top: 15px;
            }

        input[type="text"] {
            width: 250px;
        }

        #btnUyeOl {
            /*clear komutu ile önceki divlerin sola yaslanarak sıralanmasında, butonun bu yaslanmaya
            uymayıp alt satıra inmesini sağlıyoruz*/
            clear: both;
            display: block;
            margin-left: 132px;
        }
    </style>

    <!--Projemizde tarih seçici kullanacağız. Bunun için Jquery ve Jqueryui den faydalanacağız.-->

    <!--Öncelikle gerekli Jquery ui kütüphanemizi ekliyoruz. Jquery kütüphanemiz Layout sayfamızda
        zaten tanımlanmış durumdadır.-->
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <!--Kütüphanelerimizin online olduğunu bu yüzden sayfa çalışırken, internet bağlantımızın aktif olması
        gerektiğini lütfen göz önünde bulundurun.-->

    <!--Tarih seçicimizi burada hazırlayacağız-->
    <script type="text/javascript">
        $(document).ready(function () {
            $("#textBoxDogum").datepicker();
        });
    </script>
}
<h2>Yeni Üyelik</h2>

<!--Html.BeginForm ile yeni bir form oluşturuyoruz ve içeriğine elemanlarımızı ekliyoruz.-->
<!--Formumuzun içinde resim yüklemesi de yapacağımız için, forma enctype = "multipart/form-data" özelliği veriyoruz-->
<!--Ayrıca normalde sistemimize doğum gününü kaydetmeyecektik, bu yüzden bir örnek olması adına Jquery ile 
    doğum tarihini alarak, yaş kontrolü yapacağız.-->
<!--Formun sunucuya gönderim yöntemini, FormMethod.Post yaptığımıza dikkat edin.
Get ve Post metodları hakkında internette araştırma yapmanızda fayda var.-->

@using (Html.BeginForm("YeniUyelik", "Uyelik", FormMethod.Post, new { enctype = "multipart/form-data", id = "formKapsayici" }))
{
    <div id="divSol">
        @Html.LabelFor(i => Model.Ad)<br /><br />
        @Html.LabelFor(i => Model.Soyad)<br /><br />
        @Html.LabelFor(i => Model.EPosta)<br /><br />
        @Html.LabelFor(i => Model.Sifre)<br /><br />
        @Html.LabelFor(i => Model.WebSite)<br /><br />

        <!--Tüm elemanlarda for takısını kullanırken doğum tarihi ve resim yüklemede kullanmadık.
            Çünkü bu iki elaman daha önce hazırladığımız Uye modeline ait değiller.
            Bu yüzden elle ekledik.-->
        @Html.Label("Doğum Tarihiniz")<br /><br />
        @Html.Label("Profil Resminiz")<br /><br />
    </div>
    <div id="divSag">
        : @Html.TextBoxFor(i => Model.Ad)<br /><br />
        : @Html.TextBoxFor(i => Model.Soyad)<br /><br />
        : @Html.TextBoxFor(i => Model.EPosta)<br /><br />
        : @Html.TextBoxFor(i => Model.Sifre)<br /><br />
        : @Html.TextBoxFor(i => Model.WebSite)<br /><br />
        : @Html.TextBox("textBoxDogum")<br /><br />

        <!--Aşağıdaki input type="file" dosya yüklemeye yarayan, html elementidir.-->
        <input type="file" id="inputFile" name="file" /> <br /><br />

    </div>
    <input type="submit" value="Üye Ol" id="btnUyeOl" />

    <!--Html.ValidationSummary ile formda oluşan geçerlilik hatalarını liste halinde gösterebiliyoruz.-->
    @Html.ValidationSummary()
}